const MQTT_DEFAULT_BROKER_URL = "ws://192.168.1.6:9001/mqtt";
const MQTT_DEFAULT_STATE_TOPIC = "esp/status";

export const MQTT_BROKER_URL =
  process.env.NEXT_PUBLIC_MQTT_BROKER_URL ?? MQTT_DEFAULT_BROKER_URL;

export const MQTT_STATE_TOPIC =
  process.env.NEXT_PUBLIC_MQTT_STATE_TOPIC ?? MQTT_DEFAULT_STATE_TOPIC;

export const MQTT_COMMAND_TOPIC =
  process.env.NEXT_PUBLIC_MQTT_COMMAND_TOPIC ?? MQTT_STATE_TOPIC;

export const MQTT_RECONNECT_PERIOD_MS = 2000;
export const MAX_TEMPERATURE_POINTS = 300;
export const DEFAULT_VISIBLE_POINTS = 60;